apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: production
type: Opaque
stringData:
  db_connection_string: "Server=inventory-mgmt-sqlserver.c2fc20q44515.us-east-1.rds.amazonaws.com,1433;Database=InventoryManagementDb;User Id=admin;Password=YourSecurePassword123!;MultipleActiveResultSets=true;TrustServerCertificate=True;"

  jwt_key: "super_secret_key_long_enough_to_be_secure_256_bits_123456"
  jwt_issuer: "InventoryManagementAPI"
  jwt_audience: "InventoryManagementFrontend"
